### ISSUE TITLE
Logos don't navigate

### ISSUE THREAD

**Issue by aravindvnair99** [mgncodes/mgncodes#1]
Clicking on the logos in your README does not redirect to the respective profiles and instead opens the image instead

**Comment by mgncodes** [comment]
I had to change it, but I forgot to. 
Anyway, thanks for reminding!

**Comment by mgncodes** [comment]
Resolved in [this commit](https://github.com/mgncodes/mgncodes/commit/c792258c25def6698d8bf45be565e892a12a0832)
